### ISSUE TITLE
Listy m3u z dodanymi kanałami z WP pilot i darmowymi strumieniami 

### ISSUE THREAD

**Issue by robertczw** [BlackGlassSkin/Polish-Vip-Tv#3]
Można prosić o miksy list m3u z NC+ go i Canal+ VOD z kanałami z wtyczki WP pilot? Może jeszcze darmowe streamy jak TV Wielkopolska i regionalne TVP3?
Byłaby wtedy kompletna lista.

**Comment by BlackGlassSkin** [comment]
brak czasu , może za jakiś czas (wp pilot działa?)
